// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbbLQRfUD2kqTj4w2qNFQkYwGEvmdGqBs',
    appId: '1:887846823637:web:f93eb86bf65cea9238245c',
    messagingSenderId: '887846823637',
    projectId: 'auth-car-rent',
    authDomain: 'auth-car-rent.firebaseapp.com',
    storageBucket: 'auth-car-rent.appspot.com',
    measurementId: 'G-CEKYZ3ZHY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8xFtOjYPoCtUPn9fJcqUIvoVwmTnEtoQ',
    appId: '1:887846823637:android:f875533ae305ad8c38245c',
    messagingSenderId: '887846823637',
    projectId: 'auth-car-rent',
    storageBucket: 'auth-car-rent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk6niMEaeHiaH4R-xeDmpGyuVnVLzXhgs',
    appId: '1:887846823637:ios:5f0768183250e40d38245c',
    messagingSenderId: '887846823637',
    projectId: 'auth-car-rent',
    storageBucket: 'auth-car-rent.appspot.com',
    iosBundleId: 'com.example.flutterCarRent1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk6niMEaeHiaH4R-xeDmpGyuVnVLzXhgs',
    appId: '1:887846823637:ios:c90c2544e88d024f38245c',
    messagingSenderId: '887846823637',
    projectId: 'auth-car-rent',
    storageBucket: 'auth-car-rent.appspot.com',
    iosBundleId: 'com.example.flutterCarRent1.RunnerTests',
  );
}
